platform :ios, '7.0'
pod 'RETableViewManager'
pod 'JSONModel'
pod 'UIScrollSlidingPages'
pod 'AFNetWorking'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage+UIButton'
pod 'RegexKitLite-NoWarning'
